version: '3'

services:
  rsrc-cpython:
    build:
      context: .
      args:
      - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
      - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/rsrc-cpython:0.1.2
    volumes:
      - ./rsrc/:/opt/rsrc/rsrc/
      - ./tests/:/opt/rsrc/tests/
      - ./README.md:/opt/rsrc/README.md
      - ./pytest.ini:/opt/rsrc/pytest.ini
      - ./.coveragerc:/opt/rsrc/.coveragerc
      - ./setup.py:/opt/rsrc/setup.py
    entrypoint: pytest
