version: '3'

services:
  rsrc-pypy:
    build:
      context: .
      args:
      - PYTHON_IMAGE=${PYPY_IMAGE_NAME}
      - PYTHON_IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/rsrc-pypy:0.0.3
    volumes:
      - ./rsrc/:/opt/rsrc/rsrc/
      - ./tests/:/opt/rsrc/tests/
      - ./README.md:/opt/rsrc/README.md
      - ./setup.cfg:/opt/rsrc/setup.cfg
      - ./.coveragerc:/opt/rsrc/.coveragerc
      - ./setup.py:/opt/rsrc/setup.py
    entrypoint: pytest
